### ISSUE TITLE
Don't work anymore for me :(

### ISSUE THREAD

**Issue by Rootzpower** [OriKerer/AirdotsDoubleTap#7]
Hello, 

When i double tap no activate personal assistant.
Already uninstall/install and nothing
Tested on android 11 and 12

**Comment by OriKerer** [comment]
Hey, I am sorry to hear that.
I was not able to reproduce the problem that you are describing (android 11 & 12).
I'm  **guessing** the issue is originating from your earbuds not opening 'voice command':
You can try activating voice command / virtual assistant without the application, to see if the earbuds function properly.

**Comment by Rootzpower** [comment]
Does you mean saying "OK Google" to active assistant?

**Comment by Rootzpower** [comment]
Yep it's was that. After enable OK Google feature when i double tap asistence came back and now i can skip track but 3 taps don't go to previous song.
Any suggestions?

**Comment by OriKerer** [comment]
I don't think you have to enable OK Google for this (mine is disabled).
I'm not sure why that solved the issue.

About triple-tap:
It's not literally triple tap - double tapping will skip backwards when the media is paused.
So you can press once to pause the media (Or pause it any other way) and then press twice.

**Comment by OriKerer** [comment]
Yes, this should work.
In your earphones it's a bit awkward because you need to press both earphones.
